### ISSUE TITLE
Get current weekly fixture

### ISSUE THREAD

**Issue by mertkahyaoglu** [mertkahyaoglu/iddaa-oran#6]

**Comment by ZgrK** [comment]
Bunu şu şekilde getirebiliriz diye düşünüyorum iddaa bunu https://www.iddaa.com/iddaa-programi-pdf-indir/ yayınlıyor her pazar akşamı ve perşembe akşamı ki bayiler salı ve cuma sabahi programlarını yayınlasın ve genel olarak içerik düzenlemesi yapılsın diye.

Kısacası 
https://www.iddaa.com/iddaa-programi-pdf-indir/ pdf adını next urlye yazınca çalışır hale geliyor

Örneğin 
Son pdf urlsı
https://www.iddaa.com/iddaa-programi-pdf-indir/24-26-ocak-2017/

Sistem için gerekli url
http://cdn.iddaa.com/iddaa/bulten/next/24-26.01.2017.html

**Comment by mertkahyaoglu** [comment]
@ZgrK Güzel bir çözüm 👍  

Dediğin gibi <https://www.iddaa.com/iddaa-programi-pdf-indir/> burdan en üsteki programın download linkini çekip gerekli formatı verip getBulten'e paslayabiliriz.
